version: '3'

volumes:
  gems:

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres@dbhost/"
    links:
      - db:dbhost
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - gems:/usr/local/bundle
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
