version: '3'

volumes:
  gems:

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - gems:/usr/local/bundle
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
