version: '3.7'

volumes:
  gems:
  pg_data:

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: pguser
  web:
    build: .
    environment:
      DATABASE_URL: "postgresql://pguser@dbhost/"
    links:
      - db:dbhost
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - gems:/usr/local/bundle
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
